#!/bin/bash

if [ ! -d .git ]; then
    echo "This script must be ran from inside the repository directory. Exiting."
    exit 1
fi

for SRC in $HOME/.wm_dotfiles/config/*; do
    DST="$HOME/.config/"$(basename "$SRC")
    if [ -L "$DST" -o ! -d "$DST" ]; then
        ln -f -s "$SRC" "$DST"
    else
        echo "$DST already exists and is not a symlink. Skipping."
    fi
done
